#ifndef CONSTANTS_MODULE
#define CONSTANTS_MODULE

/* TCP */
#define PORT 8080
#define QUEUE_SIZE 6
#define BUF_SIZE 4096
#define TIMEOUT 1000

/* SERVER */
#define SERVER_FDS 2
#define LISTEND_FD 0
#define EVENT_FD 1

/* GAME */
#define NUMBER_OF_CARDS 36
#define NUMBER_OF_INIT_CARDS 6
#define NUMBER_OF_PLAYERS 3
#define MIN_NUMBER_OF_PLAYERS 2
#define DESK_SIZE 6
#define NUMBER_OF_SUITS 4
#define ROUND_TIME 30

#endif
